env:
  - GO111MODULE=on
builds:
  - env: [CGO_ENABLED=0]
    goos: # 编译平台列表
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
archives:
  - format_overrides:
      - goos: windows
        format: zip
      - goos: linux
        format: zip
      - goos: darwin
        format: zip
  - builds_info:
      group: root
      owner: root
