env:
  - GO111MODULE=on
builds:
  - env: [CGO_ENABLED=0]
    goos: # 编译平台列表
      - linux
      - windows
      - darwin
    goarch:
      - "amd64"
      - "arm64"
checksum:
  name_template: "checksums.txt"
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      # - LICENSE.txt
      - README.md
      # - CHANGELOG.md
      - node模板.json
      - user模板.json
