name: Release

on:
  push:
    tags:
      - "*"
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.36
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          #          asset_name: ${{binary_name}}-${{ matrix.goos }}-${{ matrix.goarch }}
          ldflags: -s -w
          #          extra_files: README.md
          compress_assets: zip
